---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.embulk:embulk-util-rubytime"
      - dependency-name: "joda-time:joda-time"
      - dependency-name: "org.junit*"
